# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-31 06:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20181030_2045'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address',
            old_name='is_deleted',
            new_name='is_delete',
        ),
    ]
